### ISSUE TITLE
[BITE] 비포애프터 리팩토링, 상세보기 기능 및 분야별 한입 기능 구현

### ISSUE THREAD

**Issue by kim-jingyu** [2nnerPeace/The-Moon-Ha-Backend#69]
## 🍀 Description
비포애프터 리팩토링 및 상세보기 기능 구현, 분야별 한입 기능 구현하고자 합니다!

## ✅ Todo
- [x] 비포애프터 리팩토링
- [x] 비포애프터 상세보기
- [x] 분야별 한입 강좌 목록 조회
- [x] 분야별 한입 강좌 검색
- [x] 분야별 한입 강좌 등록

## ETC
기타사항
